### ISSUE TITLE
cannot import name 'url_quote' from 'werkzeug.urls'

### ISSUE THREAD

**Issue by ddxxy1** [ChristopheZhao/ChaGPT-API-Call#11]
大佬们这是什么情况啊？。。。

FLASK_APP = ChaGPT-API-Call-main/manager.py
FLASK_ENV = development
FLASK_DEBUG = 0
In folder C:/Users/80909/OneDrive - UTS/Desktop/hf/GPT4
C:\Python312\python.exe -m flask run 
Traceback (most recent call last):
  File "<frozen runpy>", line 189, in _run_module_as_main
  File "<frozen runpy>", line 148, in _get_module_details
  File "<frozen runpy>", line 112, in _get_module_details
  File "C:\Python312\Lib\site-packages\flask\__init__.py", line 5, in <module>
    from .app import Flask as Flask
  File "C:\Python312\Lib\site-packages\flask\app.py", line 30, in <module>
    from werkzeug.urls import url_quote
ImportError: cannot import name 'url_quote' from 'werkzeug.urls' (C:\Python312\Lib\site-packages\werkzeug\urls.py). Did you mean: 'unquote'?

Process finished with exit code 1

**Comment by ddxxy1** [comment]
我回滚了一下版本解决这个bug了

**Comment by ddxxy1** [comment]
emmmm 现在又跟我说no module named 'web_api'。但是我已经安装了。
Successfully built webapi
Installing collected packages: webapi
Successfully installed webapi-0.1



----bug报告-----
FLASK_APP = ChaGPT-API-Call-main/manager.py
FLASK_ENV = development
FLASK_DEBUG = 0
In folder C:/Users/80909/OneDrive - UTS/Desktop/hf/GPT4
C:\Python312\python.exe -m flask run 
Usage: python -m flask run [OPTIONS]
Try 'python -m flask run --help' for help.

Error: While importing 'ChaGPT-API-Call-main.manager', an ImportError was raised:

Traceback (most recent call last):
  File "C:\Python312\Lib\site-packages\flask\cli.py", line 218, in locate_app
    __import__(module_name)
  File "C:\Users\80909\OneDrive - UTS\Desktop\hf\GPT4\ChaGPT-API-Call-main\manager.py", line 1, in <module>
    from web_api.dialogue_api import dialogue_api_handler
ModuleNotFoundError: No module named 'web_api'


Process finished with exit code 2

**Comment by ChristopheZhao** [comment]
Hi, web_api is sub dir in this project, you needn't install webapi package , you can check if __init__.py file has contains in the webapi dir. If it contained, the you can use this command to check the sys path:
`import sys
print(sys.path)`
make sure the command execute in the root dir of project.
